# --- NUEVA CONEXION A RAILWAY DESDE DOCKER ---
spring.datasource.url=jdbc:postgresql://junction.proxy.rlwy.net:43570/railway
spring.datasource.username=postgres
spring.datasource.password=XXgXxhhEWFQtCcegiohiuXBvjUHkmVUn


spring.datasource.driver-class-name=org.postgresql.Driver
# Cambia 'update' o 'create' por 'none' o 'validate'
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=never
