server.port=8080

# Conexion a la BD en Railway
spring.datasource.url=jdbc:postgresql://junction.proxy.rlwy.net:43570/railway
spring.datasource.username=postgres
spring.datasource.password=XXgXxhhEWFQtCcegiohiuXBvjUHkmVUn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.separator=^^

# Minimo 32 caracteres para HS256 (jjwt 0.12+)
jwt.secret=cafetito-secret-key-2025-mas-de-32-chars
jwt.expiration-ms=86400000
spring.web.cors.allowed-origins=http://localhost:4200
